name: Build Desktop Apps (Windows & macOS)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build_cmd: npx electron-builder --win --publish always
          - os: macos-latest
            build_cmd: npx electron-builder --mac --publish always
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Electron JS
        run: npm run build:electron

      - name: Build & Publish App
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ${{ matrix.build_cmd }}
